apiVersion: v1
kind: Service
metadata:
  name: sample-boot
spec:
  selector:
    app: sample-boot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30101
  type: NodePort